;[
  {
    car_id: 'lancer',
    fullName: 'Mitsubishi Lancer Evolution',
    nickName: '三菱',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'z4',
    fullName: 'BMW Z4 LCI E89',
    nickName: 'Z4',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'lt',
    fullName: 'Chevrolet Camaro LT',
    nickName: 'LT',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: '370',
    fullName: 'Nissan 370Z Nismo',
    nickName: '370',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'srt8',
    fullName: 'Dodge Challenger SRT8',
    nickName: 'srt8',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'gtx',
    fullName: 'KTM X-Bow GTX',
    nickName: 'GTX',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'xl',
    fullName: 'Volkswagen XL Sport Concept',
    nickName: '大众',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'hommage',
    fullName: 'BMW 3.0 CSL Hommage',
    nickName: '宝马3.0',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: '50th',
    fullName: 'Chevrolet Camaro ZL1 50TH Edition',
    nickName: '50th',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'ds',
    fullName: 'DS Automobiles DS E-Tense',
    nickName: 'DS',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'boxster',
    fullName: 'Porsche Boxster 25th',
    nickName: 'Boxster',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'rc',
    fullName: 'Nissan Leaf Nismo RC',
    nickName: 'RC',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'i8',
    fullName: 'BMW i8 Roadster',
    nickName: 'i8',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'davinci',
    fullName: 'Italdesign Davinci',
    nickName: '达芬奇',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'dezir',
    fullName: 'Renault Dezir',
    nickName: 'Dezir',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'sr1',
    fullName: 'Peugeot SR1',
    nickName: 'SR1',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'infiniti',
    fullName: 'Infiniti Project Black S',
    nickName: '英菲尼迪',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'emeya',
    fullName: 'Lotus Emeya',
    nickName: 'Emeya',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'carrerars',
    fullName: 'Porsche 911 Carrera RS 3.8',
    nickName: 'Carrera RS',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'ioniq',
    fullName: 'Hyundai Ioniq 5 N',
    nickName: '5N',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'emira',
    fullName: 'Lotus Emira',
    nickName: 'Emira',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'countach',
    fullName: 'Lamborghini Countach 25th Anniversary',
    nickName: '康塔什',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'praga',
    fullName: 'Praga R1',
    nickName: 'Praga',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'g60',
    fullName: 'Ginetta G60',
    nickName: 'G60',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: '004c',
    fullName: 'Glickenhaus 004C🔑',
    nickName: '004C',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'giulia',
    fullName: 'Alfa Romeo Giulia GTAm🔑',
    nickName: 'Giulia',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'supraracing',
    fullName: 'Toyota GR Supra Racing Concept',
    nickName: 'Supra',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'e1400',
    fullName: 'Ford Mustang Mach-E1400🔑',
    nickName: '电马',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'evo37',
    fullName: 'Kimera EVO37🔑',
    nickName: 'EVO37',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '410',
    fullName: 'Lotus Evora Sport 410',
    nickName: '大莲花',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: '392',
    fullName: 'Dodge Challenger 392 Hemi Scat Pack',
    nickName: '392',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: '911',
    fullName: 'Porsche 911 GTS Coupe',
    nickName: '911GTS',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'amg',
    fullName: 'Mercedes-Benz AMG GT S',
    nickName: 'AMG',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'db11',
    fullName: 'Aston Martin DB11',
    nickName: 'DB11',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: '718',
    fullName: 'Porsche 718 Cayman',
    nickName: '718',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: '220',
    fullName: 'Lotus Elise Sprint 220',
    nickName: '小莲花',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'm4',
    fullName: 'BMW M4 GTS',
    nickName: 'm4',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'svr',
    fullName: 'Jaguar F-Type SVR',
    nickName: '捷豹',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'gt350r',
    fullName: 'Ford Shelby GT350R',
    nickName: '野马',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'targa',
    fullName: 'Porsche 911 Targa 4S',
    nickName: 'Targa',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'civic',
    fullName: 'Honda Civic Type-R',
    nickName: '思域',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'beast',
    fullName: 'Rezvani Beast X',
    nickName: '野兽',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'griffith',
    fullName: 'TVR Griffith',
    nickName: 'TVR',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'gr-1',
    fullName: 'Ford Shelby GR-1',
    nickName: '大野马',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'trezor',
    fullName: 'Renault TreZor',
    nickName: 'TreZor',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'xkr-s',
    fullName: 'Jaguar XKR-S GT',
    nickName: 'XKR',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'taycan',
    fullName: 'Porsche Taycan Turbo S',
    nickName: '电蛙',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'v12',
    fullName: 'Aston Martin V12 Speedster',
    nickName: 'V12',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'continental',
    fullName: 'Bentley Continental GT3🔑',
    nickName: '欧陆 GT3',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'citroën_ds_survolt',
    fullName: 'Citroën DS Survolt',
    nickName: 'DS龙',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'c7r',
    fullName: 'Chevrolet Corvette C7.R🔑',
    nickName: 'C7R',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'f50',
    fullName: 'Ferrari F50',
    nickName: 'F50',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'mk500',
    fullName: 'Bolwell MK X Nagari 500',
    nickName: 'MK500',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'd8',
    fullName: 'Donkervoort D8 GTO Individual Series',
    nickName: 'D8',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'vwer',
    fullName: 'Volkswagen Electric R🔑',
    nickName: '大众电R',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'clk',
    fullName: 'Mercedes-Benz CLK-GTR',
    nickName: 'CLK GTR',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'mc12',
    fullName: 'Maserati MC12🔑',
    nickName: 'MC12',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'arashaf10',
    fullName: 'Arash AF10',
    nickName: '阿拉什',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: '370zneon',
    fullName: 'Nissan 370Z Nismo Neon Edition🔑',
    nickName: '370霓虹',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'saleens1',
    fullName: 'Saleen S1',
    nickName: '萨林S1',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: '91150',
    fullName: 'Porsche 911 50 Years Porsche Design',
    nickName: '911 50周年',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'missionr',
    fullName: 'Porsche Mission R',
    nickName: 'Mission R',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'xjr-15',
    fullName: 'Jaguar XJR-15',
    nickName: 'XJR-15',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'sagaris',
    fullName: 'TVR Sagaris',
    nickName: 'Sagaris',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'supra',
    fullName: 'Toyota GR Supra 2023',
    nickName: 'Supra2023',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'visionamg',
    fullName: 'Mercedes-Benz 2022 Showcar Vision AMG',
    nickName: 'VisionAMG',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'af8',
    fullName: 'Arash AF8 Falcon Edition🔑',
    nickName: 'AF8',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'project8',
    fullName: 'Jaguar XE SV Project 8',
    nickName: 'Project8',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'monza',
    fullName: 'Ferrari Monza SP1',
    nickName: 'Monza',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'ares',
    fullName: 'Ares S1🔑',
    nickName: 'Ares',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'panamera',
    fullName: 'Porsche Panamera Turbo S',
    nickName: '帕拉梅拉',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'dsp',
    fullName: 'DS Automobiles DS E-Tense Performance',
    nickName: 'DSP',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'mbbs',
    fullName: 'Mercedes-Benz Mercedes-AMG GT Black Series🔑',
    nickName: '梅奔BS',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'bohema',
    fullName: 'Praga Bohema',
    nickName: 'Bohema',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'mc20gt2',
    fullName: 'Maserati MC20 GT2🔑',
    nickName: 'MC20GT2',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'p900',
    fullName: 'De Tomaso P900',
    nickName: 'P900',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '770',
    fullName: 'Aston Martin DBS 770 Ultimate🔑',
    nickName: 'DBS 770',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'lamborghini_huracan_sterrato',
    fullName: 'Lamborghini Huracan Sterrato',
    nickName: '飓风 Sterrato',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '296',
    fullName: 'Ferrari 296 GTB🔑',
    nickName: '296GTB',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'daytonasp3',
    fullName: 'Ferrari Daytona SP3🔑',
    nickName: '戴通纳SP3',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'zgt4',
    fullName: 'Nissan Z GT4',
    nickName: 'Z GT4',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'w70',
    fullName: 'Exotic Rides W70',
    nickName: 'W70',
    isKeyCar: false,
    rankLimits: [],
    star: 3,
  },
  {
    car_id: 'fordgt',
    fullName: 'Ford GT',
    nickName: '福特GT',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'acr',
    fullName: 'Dodge Viper ACR',
    nickName: 'ACR',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'asterion',
    fullName: 'Lamborghini Asterion',
    nickName: '蓝牛',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'vulcan',
    fullName: 'Aston Martin Vulcan',
    nickName: '火神',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'rtr',
    fullName: 'Ford Mustang RTR Spec 5 10th Anniv.',
    nickName: '野马RTR',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'h2',
    fullName: 'Pininfarina H2 Speed',
    nickName: 'H2',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: '911gt1',
    fullName: 'Porsche 911 GT1 Evolution',
    nickName: '911GT1',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'roma',
    fullName: 'Ferrari Roma',
    nickName: '罗马',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'ass',
    fullName: 'Artega Scalo SuperErelletra',
    nickName: 'ASS',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'gtr',
    fullName: 'Nissan GT-R Nismo',
    nickName: 'GTR',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'cien',
    fullName: 'Cadillac Cien Concept',
    nickName: '塞恩',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'valour',
    fullName: 'Aston Martin Valour🔑',
    nickName: 'Valour',
    isKeyCar: true,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'mk2',
    fullName: 'Ford GT MKII🔑',
    nickName: 'MK2',
    isKeyCar: true,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'nsx',
    fullName: 'Acura 2017 NSX',
    nickName: '讴歌',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'alfieri',
    fullName: 'Maserati Alfieri',
    nickName: '玛莎',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'j50',
    fullName: 'Ferrari J50',
    nickName: 'J50',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'huracansto',
    fullName: 'Lamborghini Huracan STO',
    nickName: 'STO',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'huracanste',
    fullName: 'Lamborghini Huracan Super Trofeo Evo🔑',
    nickName: '小小牛',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'artura',
    fullName: 'McLaren Artura',
    nickName: 'Artura',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'sarthe',
    fullName: 'Vencer Sarthe',
    nickName: '剃刀',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'zerouno',
    fullName: 'ItalDesign Zerouno',
    nickName: '假牛',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'vipergts',
    fullName: 'Dodge Viper GTS',
    nickName: '紫蛇',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'continentalgt',
    fullName: 'Bentley Continental GT Speed',
    nickName: '欧陆',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: '488',
    fullName: 'Ferrari 488 GTB',
    nickName: '488',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'bacalar',
    fullName: 'Bentley Mulliner Bacalar',
    nickName: 'Bacalar',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'f40',
    fullName: 'Ferrari F40',
    nickName: 'F40',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'rrturbo',
    fullName: 'ATS Automobili Corsa RRTurbo🔑',
    nickName: 'RRTurbo',
    isKeyCar: true,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'slr',
    fullName: 'Mercedes-Benz SLR McLaren',
    nickName: 'SLR',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'motion',
    fullName: 'Kepler Motion',
    nickName: '开普勒',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'furai',
    fullName: 'Mazda Furai',
    nickName: '风籁',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '718gt4',
    fullName: 'Porsche 718 Cayman GT4 ClubSport🔑',
    nickName: '718GT4',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'dbs',
    fullName: 'Aston Martin DBS SuperLeggera',
    nickName: 'DBS',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'mclarengt',
    fullName: 'McLaren GT🔑',
    nickName: '迈凯伦GT',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'xxe',
    fullName: 'Ferrari 599XX EVO🔑',
    nickName: 'XXE',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'drakogte',
    fullName: 'Drako GTE',
    nickName: '德拉科GTE',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'bt62',
    fullName: 'Brabham BT62🔑',
    nickName: 'BT62',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '911turbo',
    fullName: 'Porsche 911 Turbo 50 Years',
    nickName: '911 Turbo',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'elva',
    fullName: 'McLaren Elva',
    nickName: 'Elva',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'rs01',
    fullName: 'Renault R.S. 01🔑',
    nickName: '雷诺RS',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'db12',
    fullName: 'Aston Martin DB12',
    nickName: 'DB12',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'nsxgt3',
    fullName: 'Acura NSX GT3 EVO🔑',
    nickName: 'NSX GT3',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'r390',
    fullName: 'Nissan R390 GT1🔑',
    nickName: 'R390',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'legostingray',
    fullName: 'LEGO Technic Chevrolet Corvette Stingray',
    nickName: '乐高C8R',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '765lt',
    fullName: 'McLaren 765LT',
    nickName: '765LT',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'm4gt3',
    fullName: 'BMW M4 GT3',
    nickName: 'M4 GT3',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'miura',
    fullName: 'Lamborghini Miura Concept🔑',
    nickName: 'Miura',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'eb110',
    fullName: 'Bugatti EB110🔑',
    nickName: 'EB110',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'one77',
    fullName: 'Aston Martin One77',
    nickName: 'One77',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'mc20',
    fullName: 'Maserati MC20🔑',
    nickName: 'MC20',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'stingray',
    fullName: 'Chevrolet Corvette Stingray',
    nickName: 'C8',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'diablo',
    fullName: 'Lamborghini Diablo GT',
    nickName: 'Diablo',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'lego_technic_bmw_m4_gt3_evo',
    fullName: 'LEGO Technic BMW M4 GT3 EVO',
    nickName: '乐高 M4',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'ferrari_f12_berlinetta',
    fullName: 'Ferrari F12 Berlinetta',
    nickName: 'Berlinetta',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'reventon',
    fullName: 'Lamborghini Reventon Roadster🔑',
    nickName: '雷文顿',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'fegen2',
    fullName: 'Formula E Gen 2 Asphalt Edition',
    nickName: 'FE Gen 2',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'mhybrid',
    fullName: 'BMW M Hybrid V8🔑',
    nickName: 'M Hybrid',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sc63',
    fullName: 'Lamborghini SC63🔑',
    nickName: 'SC63',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'vantage',
    fullName: 'Aston Martin V12 Vantage 2022',
    nickName: 'Vantage',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '600lt',
    fullName: 'McLaren 600LT Spider',
    nickName: '600LT',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'solus',
    fullName: 'Mclaren Solus GT🔑',
    nickName: 'Solus GT',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'grssc',
    fullName: 'Toyota GR Super Sport Concept🔑',
    nickName: 'GR concept',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'invencible',
    fullName: 'Lamborghini Invencible',
    nickName: '无敌牛',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'evo',
    fullName: 'Lamborghini Huracan EVO Spyder',
    nickName: 'EVO',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'gt65',
    fullName: 'FV Frangivento GT65🔑',
    nickName: 'GT65',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'sesto',
    fullName: 'Lamborghini Sesto Elemento',
    nickName: '第六元素',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'mk4',
    fullName: 'Ford GT MK IV🔑',
    nickName: 'MK4🔑',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'legorevuelto',
    fullName: 'LEGO Technic Lamborghini Revuelto',
    nickName: '乐高R牛',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'apolloevo',
    fullName: 'Apollo EVO',
    nickName: '菠萝EVO',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'er9',
    fullName: 'Lotus E-R9🔑',
    nickName: 'ER9',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'revuelto',
    fullName: 'Lamborghini Revuelto',
    nickName: 'R牛',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'laferrari',
    fullName: 'Ferrari LaFerrari',
    nickName: '拉法',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'legofxxk',
    fullName: 'LEGO Technic Ferrari FXX K',
    nickName: '乐高FXX K',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '003',
    fullName: 'Glickenhaus 003S',
    nickName: '003',
    isKeyCar: false,
    rankLimits: [],
    star: 4,
  },
  {
    car_id: 'n',
    fullName: 'Apollo N',
    nickName: '菠萝',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'p1',
    fullName: 'McLaren P1™',
    nickName: 'P1',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'barchetta',
    fullName: 'Pagani Zonda HP Barchetta🔑',
    nickName: 'Barchetta',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'centenario',
    fullName: 'Lamborghini Centenario',
    nickName: '百年牛',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'f12tdf',
    fullName: 'Ferrari F12tdf',
    nickName: 'TDF',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'gallardo',
    fullName: 'Lamborghini Gallardo LP 560-4',
    nickName: '盖拉多',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sv',
    fullName: 'Lamborghini Aventador SV Coupe',
    nickName: 'SV',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'fxxk',
    fullName: 'Ferrari FXX K',
    nickName: 'FXXK',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'legosennagtr',
    fullName: 'LEGO Technic Mclaren Senna GTR',
    nickName: '乐高塞纳GTR',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'autentica',
    fullName: 'Lamborghini Autentica🔑',
    nickName: 'Autentica',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'c-x75',
    fullName: 'Jaguar C-X75',
    nickName: '大捷豹',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'cgs',
    fullName: 'Chevrolet Corvette Grand Sport',
    nickName: '五菱',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '33',
    fullName: 'Arrinera Hussarya 33',
    nickName: '33',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'legovalkyrie',
    fullName: 'LEGO Technic Aston Martin Valkyrie',
    nickName: '乐高女武神',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'ap-0',
    fullName: 'Apex AP-0',
    nickName: 'AP-0',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'murcielago',
    fullName: 'Lamborghini Murcielago LP 640 Roadster',
    nickName: '蝙蝠',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '1v10',
    fullName: 'VLF Force 1 V10',
    nickName: 'VLF',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '812',
    fullName: 'Ferrari 812 SuperFast',
    nickName: '812',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'ie',
    fullName: 'Apollo IE',
    nickName: 'IE',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '550',
    fullName: 'Sin R1 550',
    nickName: 'SIN',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'gt12',
    fullName: 'Aston Martin Vantage GT12',
    nickName: 'GT12',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'avj',
    fullName: 'Lamborghini Aventador J',
    nickName: 'AVJ',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'speirling',
    fullName: 'Mcmurtry Speirling',
    nickName: 'Speirling',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'carrera',
    fullName: 'Porsche Carrera GT',
    nickName: '卡雷拉',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'enzo',
    fullName: 'Ferrari Enzo Ferrari',
    nickName: '恩佐',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '911gt3',
    fullName: 'Porsche 911 GT3 RS',
    nickName: '911GT3',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'at96',
    fullName: 'TechRules AT96 Track Version🔑',
    nickName: '腾风',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sennagtr',
    fullName: 'McLaren Senna GTR',
    nickName: '塞纳GTR',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'onyx',
    fullName: 'Peugeot Onyx',
    nickName: '标致',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'zr1',
    fullName: 'Chevrolet Corvette ZR1',
    nickName: '大五菱',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'scv12',
    fullName: 'Lamborghini Essenza SCV12🔑',
    nickName: 'SCV12',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'berlinetta',
    fullName: 'Puritalia Berlinetta',
    nickName: 'Berlinetta',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'sc18',
    fullName: 'Lamborghini SC18🔑',
    nickName: 'SC18',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'svj',
    fullName: 'Lamborghini Aventador SVJ Roadster',
    nickName: 'SVJ',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'fegen3',
    fullName: 'Formula E Gen 3 EVO Championship Edition🔑',
    nickName: 'FE Gen3',
    isKeyCar: true,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'gtcny',
    fullName: 'Ford GT CNY Edition',
    nickName: 'GT春节版',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '488gtbevo',
    fullName: 'Ferrari 488 Challenge EVO🔑',
    nickName: '488EVO',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'tachyon',
    fullName: 'Raesr Tachyon Speed🔑',
    nickName: '超光速',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'citroengt',
    fullName: 'Citroen GT by Citroen',
    nickName: '雪铁龙GT',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'cinque',
    fullName: 'Pagani Zonda Cinque',
    nickName: 'Cinque',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'zagato',
    fullName: 'Aston Martin DBS GT Zagato',
    nickName: 'Zagato',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ccgshe',
    fullName: 'Chevrolet Corvette Grand Sport Halloween Edition',
    nickName: '五菱万圣版',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'automobili_pininfarina_battista_edizione_nino_farina',
    fullName: 'Automobili Pininfarina Battista Edizione Nino Farina',
    nickName: '秋王特别版',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'gtr-50',
    fullName: 'Nissan GTR-50 Italdesign',
    nickName: 'GTR-50',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'zondar',
    fullName: 'Pagani Zonda R🔑',
    nickName: '风之子',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '9x8',
    fullName: 'Peugeot 9x8',
    nickName: '9x8',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sabre',
    fullName: 'McLaren Sabre',
    nickName: 'Sabre',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '007s',
    fullName: 'Glickenhaus 007S🔑',
    nickName: '007S',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'gtrneon',
    fullName: 'Nissan GT-R Neon Edition',
    nickName: '霓虹GTR',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '935',
    fullName: 'Porsche 935(2019)🔑',
    nickName: '935',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'victor',
    fullName: 'Aston Martin Victor',
    nickName: 'Victor',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'huayrar',
    fullName: 'Pagani Huayra R',
    nickName: 'Huayra R',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '650s',
    fullName: 'Mclaren 650S GT3',
    nickName: '650S',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sf90xx',
    fullName: 'Ferrari SF90 XX Stradale',
    nickName: 'SF90XX',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'interceptor',
    fullName: 'Security Interceptor',
    nickName: '拦路虎',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'utopia',
    fullName: 'Pagani Utopia Coupe🔑',
    nickName: '乌托邦',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'supersnake',
    fullName: 'Ford Shelby Super Snake',
    nickName: '超级蛇',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'temerario',
    fullName: 'Lamborghini Temerario',
    nickName: 'Temerario',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'asfane',
    fullName: 'FV Frangivento Asfane🔑',
    nickName: 'Asfane',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'xjr',
    fullName: 'Jaguar XJR-9',
    nickName: 'XJR-9',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'm600',
    fullName: 'Noble M600 Speedster',
    nickName: 'M600',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'valhalla',
    fullName: 'Aston Martin Valhalla Concept Car',
    nickName: '英灵殿',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'bev',
    fullName: 'Lexus Electrified Sport Concept',
    nickName: 'lexus concept',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'amgone',
    fullName: 'Mercedes-Benz Merceds-AMG One🔑',
    nickName: 'AMG One',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '499p',
    fullName: 'Ferrari 499P Modificata🔑',
    nickName: '499P',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'p72',
    fullName: 'De Tomaso P72🔑',
    nickName: 'P72',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'vision111',
    fullName: 'Mercedes-Benz Vision One-Eleven🔑',
    nickName: 'Vision 111',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'b95',
    fullName: 'Automobili Pininfarina B95',
    nickName: 'B95',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'vulcano',
    fullName: 'Icona Vulcano Titanium',
    nickName: '火山',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'lykan',
    fullName: 'W Motors Lykan HyperSport',
    nickName: '狼崽',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: '918',
    fullName: 'Porsche 918 Spyder',
    nickName: '918',
    isKeyCar: false,
    rankLimits: [],
    star: 5,
  },
  {
    car_id: 'vanda',
    fullName: 'Vanda Electrics Dendrobium',
    nickName: '万达',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '570',
    fullName: 'McLaren 570S Spider',
    nickName: '570',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'veneno',
    fullName: 'Lamborghini Veneno',
    nickName: '毒药',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'atsgt',
    fullName: 'ATS Automobili GT',
    nickName: 'ATS GT',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'xj220',
    fullName: 'Jaguar XJ220 TWR🔑',
    nickName: 'XJ220',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'egoista',
    fullName: 'Lamborghini Egoista',
    nickName: '自私',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'me412',
    fullName: 'Chrysler ME412',
    nickName: 'ME412',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '911gt2',
    fullName: 'Porsche 911 GT2 RS ClubSport🔑',
    nickName: '911GT2',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'bc',
    fullName: 'Pagani Huayra BC',
    nickName: 'BC',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'aperta',
    fullName: 'Ferrari LaFerrari Aperta',
    nickName: '黑拉法',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'tsr-s',
    fullName: 'Zenvo TSR-S🔑',
    nickName: 'TSR-S',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'f1',
    fullName: 'Mclaren F1 LM🔑',
    nickName: 'F1',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'f8',
    fullName: 'Ferrari F8 Tributo',
    nickName: 'F8',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'akylone',
    fullName: 'Genty Akylone',
    nickName: '阿卡龙',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sc20',
    fullName: 'Lamborghini SC20🔑',
    nickName: 'SC20',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'w12',
    fullName: 'Volkswagen W12 Coupe🔑',
    nickName: 'W12',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'nemesis',
    fullName: 'Trion Nemesis',
    nickName: '复仇',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'spano',
    fullName: 'Spania GTA 2015 GTA Spano',
    nickName: 'Spano',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sorpasso',
    fullName: 'FV Frangivento Sorpasso GT3🔑',
    nickName: 'FV',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'terzo',
    fullName: 'Lamborghini Terzo Millennio',
    nickName: '电牛',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'senna',
    fullName: 'McLaren Senna',
    nickName: '塞纳',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'veyron',
    fullName: 'Bugatti Veyron 16.4 Grand Sport Vitesse',
    nickName: '威龙',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'evija',
    fullName: 'Lotus Evija',
    nickName: '电莲',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '1789',
    fullName: 'Vision 1789',
    nickName: '1789',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'teorema',
    fullName: 'Pininfarina Teorema',
    nickName: 'Teorema',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'fenyr',
    fullName: 'W Motors Fenyr SuperSport',
    nickName: '狼王',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'valkyrie',
    fullName: 'Aston Martin Valkyrie',
    nickName: '女武神',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'c1',
    fullName: 'Rimac Concept_One',
    nickName: 'C_One',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ts1',
    fullName: 'Zenvo TS1 GT Anniversary',
    nickName: '自燃车',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'cs',
    fullName: 'Rimac Concept S',
    nickName: 'CS',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sf90',
    fullName: 'Ferrari SF90 Stradale',
    nickName: 'SF90',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'battista',
    fullName: 'Automobili Pininfarina Battista',
    nickName: '秋王',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'at96db',
    fullName: 'TechRules AT96 Dragon Boat Edition🔑',
    nickName: '腾风龙舟',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'imola',
    fullName: 'Pagani Imola',
    nickName: '伊莫拉',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'naran',
    fullName: 'Naran Hyper Coupe',
    nickName: '纳兰',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'lpi800',
    fullName: 'Lamborghini Countach LPI 800-4🔑',
    nickName: '新康塔什',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ep9',
    fullName: 'Nio EP9',
    nickName: 'EP9',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'imperium',
    fullName: 'Arash Imperium🔑',
    nickName: 'Imperium',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'nvision74',
    fullName: 'Hyundai N Vision 74🔑',
    nickName: 'N74',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'speedtail',
    fullName: 'McLaren Speedtail',
    nickName: '速尾',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ff01',
    fullName: 'Faraday Future FFZero1',
    nickName: 'FF01',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'divo',
    fullName: 'Bugatti Divo',
    nickName: 'Divo',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'regera',
    fullName: 'Koenigsegg Regera',
    nickName: '统治',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'gt32023',
    fullName: 'Porsche GT3 RS 2023🔑',
    nickName: 'GT3 2023',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'saleens7',
    fullName: 'Saleen S7 twin Turbo',
    nickName: '萨林S7',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'lykanneon',
    fullName: 'W Motors Lykan HyperSport Neon Edition',
    nickName: '霓虹狼崽',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ultimars',
    fullName: 'Ultima RS🔑',
    nickName: 'Ultima RS',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'w_motors_fenyr_super_sport_cny_edition',
    fullName: 'W Motors Fenyr Super Sport CNY Edition',
    nickName: '狼王春节版',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '5fd',
    fullName: 'Ford Mustang RTR Spec 5-FD',
    nickName: 'rtr 5-fd',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'drakuma',
    fullName: 'Ajlani Drakuma',
    nickName: 'Drakuma',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'fordp1',
    fullName: 'Ford Team FordZilla P1',
    nickName: '福特P1',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'aero',
    fullName: 'SSC Ultimate Aero TT',
    nickName: 'Aero TT',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'inferno',
    fullName: 'Inferno Automobili Inferno',
    nickName: '地狱',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'torino',
    fullName: 'Torino Design Super Sport🔑',
    nickName: '都灵',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'chiron',
    fullName: 'Bugatti Chiron',
    nickName: '肥龙',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'bxr',
    fullName: 'BXR Bailey Blade GT1',
    nickName: 'BXR',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'legochiron',
    fullName: 'LEGO Technic Bugatti Chiron Pur Sport',
    nickName: '乐高 PS龙',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ts900',
    fullName: 'Tushek TS 900 Racer Pro',
    nickName: 'TS900',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'millecavalli',
    fullName: 'Mazzanti Evantra Millecavalli',
    nickName: '皇后',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '1mw',
    fullName: 'Toroidion 1MW',
    nickName: '1MW',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'pursport',
    fullName: 'Bugatti Chiron Pur Sport🔑',
    nickName: 'PS龙',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'jesko',
    fullName: 'Koenigsegg Jesko🔑',
    nickName: 'Jesko',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'centodieci',
    fullName: 'Bugatti Centodieci🔑',
    nickName: '白龙',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sian',
    fullName: 'Lamborghini Sian FKP 37🔑',
    nickName: 'Sian',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'owl',
    fullName: 'Aspark Owl',
    nickName: '猫头鹰',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'aglaia',
    fullName: 'Raesr Aglaia🔑',
    nickName: 'Aglaia',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'c2',
    fullName: 'Rimac Nevera🔑',
    nickName: 'C2',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ssc',
    fullName: 'SSC Tuatara',
    nickName: '大蜥蜴',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'agerars',
    fullName: 'Koenigsegg Agera RS',
    nickName: 'Agera RS',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'htt',
    fullName: 'HTT Locus Plethore LC750',
    nickName: 'HTT',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'venomgt',
    fullName: 'Hennessey Venom GT',
    nickName: '毒液GT',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'lykansecurity',
    fullName: 'W Motors Lykan Security',
    nickName: '拦路狼',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'ccxr',
    fullName: 'Koenigsegg CCXR🔑',
    nickName: 'CCXR',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'lvn',
    fullName: 'Bugatti LA Voiture Noire🔑',
    nickName: '黑龙',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'one1',
    fullName: 'Koenigsegg One:1🔑',
    nickName: '旺旺',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'vayanne',
    fullName: 'Deus Vayanne',
    nickName: 'Vayanne',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'gemera',
    fullName: 'Koenigsegg Gemera🔑',
    nickName: 'Gemera',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'mistral',
    fullName: 'Bugatti Mistral🔑',
    nickName: 'Mistral',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'tur',
    fullName: 'Zenvo Aurora Tur',
    nickName: '极光',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'venomf5',
    fullName: 'Hennessey Venom F5',
    nickName: '毒液F5',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'cc850',
    fullName: 'Koenigsegg CC850🔑',
    nickName: 'CC850',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: '21c',
    fullName: 'Czinger 21C',
    nickName: '21C',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'mosler_super_gt',
    fullName: 'Mosler Super GT',
    nickName: '莫斯勒 SuperGT',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'tartarus',
    fullName: 'Raesr Tartarus',
    nickName: 'Tartarus',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'sixteen',
    fullName: 'Devel Sixteen🔑',
    nickName: '恶魔',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'tuatarastriker',
    fullName: 'SSC Tuatara Striker🔑',
    nickName: 'SSC Striker',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'silver',
    fullName: 'Mercedes-Benz Silver Lightning🔑',
    nickName: '银电',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'bolide',
    fullName: 'Bugatti Bolide🔑',
    nickName: '玻璃龙',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'chiron300',
    fullName: 'Bugatti Chiron Super Sport 300+🔑',
    nickName: '300+',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'neverar',
    fullName: 'Rimac Nevera R🔑',
    nickName: 'Nevera R',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'hennessey_venom_f5_evolution',
    fullName: 'Hennessey Venom F5 Revolution',
    nickName: '毒液 F5 R',
    isKeyCar: true,
    rankLimits: [],
    star: 6,
  },
  {
    car_id: 'jkab',
    fullName: 'Koenigsegg Jesko Absolut',
    nickName: '杰皇',
    isKeyCar: false,
    rankLimits: [],
    star: 6,
  },
]
