;[
  {
    car_id: 'lancer',
    fullName: 'Mitsubishi Lancer Evolution',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1381,
    carClass: 'D',
    rewardBP: 5,
  },
  {
    car_id: 'z4',
    fullName: 'BMW Z4 LCI E89',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1476,
    carClass: 'D',
    rewardBP: 5,
  },
  {
    car_id: 'lt',
    fullName: 'Chevrolet Camaro LT',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1546,
    carClass: 'D',
    rewardBP: 5,
  },
  {
    car_id: '370',
    fullName: 'Nissan 370Z Nismo',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1662,
    carClass: 'D',
    rewardBP: 10,
  },
  {
    car_id: 'srt8',
    fullName: 'Dodge Challenger SRT8',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1683,
    carClass: 'D',
    rewardBP: 15,
  },
  {
    car_id: 'gtx',
    fullName: 'KTM X-Bow GTX',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1738,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: 'xl',
    fullName: 'Volkswagen XL Sport Concept',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1814,
    carClass: 'D',
    rewardBP: 15,
  },
  {
    car_id: '3.0',
    fullName: 'BMW 3.0 CSL Hommage',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1827,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: '50th',
    fullName: 'Chevrolet Camaro ZL1 50TH Edition',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1971,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: 'ds',
    fullName: 'DS Automobiles DS E-Tense',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 1976,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: 'boxster',
    fullName: 'Porsche Boxster 25th',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 1985,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: 'rc',
    fullName: 'Nissan Leaf Nismo RC',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2101,
    carClass: 'D',
    rewardBP: 30,
  },
  {
    car_id: 'i8',
    fullName: 'BMW i8 Roadster',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2122,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: 'davinci',
    fullName: 'Italdesign Davinci',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2210,
    carClass: 'D',
    rewardBP: 20,
  },
  {
    car_id: 'dezir',
    fullName: 'Renault Dezir',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2213,
    carClass: 'D',
    rewardBP: 25,
  },
  {
    car_id: 'sr1',
    fullName: 'Peugeot SR1',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2307,
    carClass: 'D',
    rewardBP: 25,
  },
  {
    car_id: 'infiniti',
    fullName: 'Infiniti Project Black S',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2371,
    carClass: 'D',
    rewardBP: 30,
  },
  {
    car_id: 'emira',
    fullName: 'Lotus Emira',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2612,
    carClass: 'D',
    rewardBP: 25,
  },
  {
    car_id: 'countach',
    fullName: 'Lamborghini Countach 25th Anniversary',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2618,
    carClass: 'D',
    rewardBP: 25,
  },
  {
    car_id: 'praga',
    fullName: 'Praga R1',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2624,
    carClass: 'D',
    rewardBP: 25,
  },
  {
    car_id: 'g60',
    fullName: 'Ginetta G60',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2632,
    carClass: 'D',
    rewardBP: 30,
  },
  {
    car_id: '004c',
    fullName: 'Glickenhaus 004C🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 2840,
    carClass: 'D',
    rewardBP: 30,
  },
  {
    car_id: 'e1400',
    fullName: 'Ford Mustang Mach-E1400🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3097,
    carClass: 'D',
    rewardBP: 30,
  },
  {
    car_id: '410',
    fullName: 'Lotus Evora Sport 410',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2123,
    carClass: 'C',
    rewardBP: 20,
  },
  {
    car_id: '392',
    fullName: 'Dodge Challenger 392 Hemi Scat Pack',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2152,
    carClass: 'C',
    rewardBP: 20,
  },
  {
    car_id: '911',
    fullName: 'Porsche 911 GTS Coupe',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2185,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: 'amg',
    fullName: 'Mercedes-Benz AMG GT S',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2281,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: 'db11',
    fullName: 'Aston Martin DB11',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2330,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: '718',
    fullName: 'Porsche 718 Cayman',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2344,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: '220',
    fullName: 'Lotus Elise Sprint 220',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2363,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: 'm4',
    fullName: 'BMW M4 GTS',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2447,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: 'svr',
    fullName: 'Jaguar F-Type SVR',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2487,
    carClass: 'C',
    rewardBP: 30,
  },
  {
    car_id: 'gt350r',
    fullName: 'Ford Shelby GT350R',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2531,
    carClass: 'C',
    rewardBP: 30,
  },
  {
    car_id: 'targa',
    fullName: 'Porsche 911 Targa 4S',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2571,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'civic',
    fullName: 'Honda Civic Type-R',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2627,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'beast',
    fullName: 'Rezvani Beast X',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2635,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'griffith',
    fullName: 'TVR Griffith',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2641,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'gr-1',
    fullName: 'Ford Shelby GR-1',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2642,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'trezor',
    fullName: 'Renault TreZor',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2646,
    carClass: 'C',
    rewardBP: 50,
  },
  {
    car_id: 'taycan',
    fullName: 'Porsche Taycan Turbo S',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2704,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'v12',
    fullName: 'Aston Martin V12 Speedster\r\n',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2733,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'continental',
    fullName: 'Bentley Continental GT3🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 2781,
    carClass: 'C',
    rewardBP: 25,
  },
  {
    car_id: 'c7r',
    fullName: 'Chevrolet Corvette C7.R🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 2836,
    carClass: 'C',
    rewardBP: 30,
  },
  {
    car_id: 'f50',
    fullName: 'Ferrari F50',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2838,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'mk500',
    fullName: 'Bolwell MK X Nagari 500',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2854,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'd8',
    fullName: 'Donkervoort D8 GTO Individual Series',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 2991,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'vwer',
    fullName: 'Volkswagen Electric R🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3062,
    carClass: 'C',
    rewardBP: 30,
  },
  {
    car_id: 'clk',
    fullName: 'Mercedes-Benz CLK-GTR',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3083,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'mc12',
    fullName: 'Maserati MC12',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3100,
    carClass: 'C',
    rewardBP: 30,
  },
  {
    car_id: 'arashaf10',
    fullName: 'Arash AF10',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3109,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: '370zneon',
    fullName: 'Nissan 370Z Nismo Neon Edition🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3121,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'saleens1',
    fullName: 'Saleen S1',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3148,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'xjr-15',
    fullName: 'Jaguar XJR-15',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3244,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'af8',
    fullName: 'Arash AF8 Falcon Edition🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3289,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'project8',
    fullName: 'Jaguar XE SV Project 8',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3289,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'monza',
    fullName: 'Ferrari Monza SP1',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3334,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'ares',
    fullName: 'Ares S1🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3377,
    carClass: 'C',
    rewardBP: 38,
  },
  {
    car_id: 'panamera',
    fullName: 'Porsche Panamera Turbo S',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3403,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'dsp',
    fullName: 'DS Automobiles DS E-Tense Performance',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 3424,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'mbbs',
    fullName: 'Mercedes-Benz Mercedes-AMG GT Black Series🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 3517,
    carClass: 'C',
    rewardBP: 35,
  },
  {
    car_id: 'w70',
    fullName: 'Exotic Rides W70',
    shortName: '',
    isKeyCar: false,
    star: 3,
    rank: 2633,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'fordgt',
    fullName: 'Ford GT',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2816,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'acr',
    fullName: 'Dodge Viper ACR',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2827,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'asterion',
    fullName: 'Lamborghini Asterion',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 2983,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'vulcan',
    fullName: 'Aston Martin Vulcan',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3000,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'h2',
    fullName: 'Pininfarina H2 Speed',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3026,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: '911gt1',
    fullName: 'Porsche 911 GT1 Evolution',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3049,
    carClass: 'B',
    rewardBP: 25,
  },
  {
    car_id: 'roma',
    fullName: 'Ferrari Roma',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3061,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'ass',
    fullName: 'Artega Scalo SuperErelletra',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3093,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'gtr',
    fullName: 'Nissan GT-R Nismo',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3144,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'cien',
    fullName: 'Cadillac Cien Concept',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3155,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'mk2',
    fullName: 'Ford GT MKII🔑',
    shortName: '',
    isKeyCar: true,
    star: 4,
    rank: 3198,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'nsx',
    fullName: 'Acura 2017 NSX',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3208,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'alfieri',
    fullName: 'Maserati Alfieri',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3209,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'j50',
    fullName: 'Ferrari J50',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3229,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'huracanste',
    fullName: 'Lamborghini Huracan Super Trofeo Evo🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3256,
    carClass: 'B',
    rewardBP: 30,
  },
  {
    car_id: 'artura',
    fullName: 'McLaren Artura',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3280,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'sarthe',
    fullName: 'Vencer Sarthe',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3290,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'zerouno',
    fullName: 'ItalDesign Zerouno',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3295,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'vipergts',
    fullName: 'Dodge Viper GTS',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3295,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'continentalgt',
    fullName: 'Bentley Continental GT Speed',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3330,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: '488',
    fullName: 'Ferrari 488 GTB',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3334,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'bacalar',
    fullName: 'Bentley Mulliner Bacalar',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3340,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'f40',
    fullName: 'Ferrari F40',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3343,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'slr',
    fullName: 'Mercedes-Benz SLR McLaren',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3389,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'rrturbo',
    fullName: 'ATS Automobili Corsa RRTurbo🔑',
    shortName: '',
    isKeyCar: true,
    star: 4,
    rank: 3389,
    carClass: 'B',
    rewardBP: 38,
  },
  {
    car_id: 'motion',
    fullName: 'Kepler Motion',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3393,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'furai',
    fullName: 'Mazda Furai',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3408,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: '718gt4',
    fullName: 'Porsche 718 Cayman GT4 ClubSport🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3415,
    carClass: 'B',
    rewardBP: 25,
  },
  {
    car_id: 'dbs',
    fullName: 'Aston Martin DBS SuperLeggera',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3423,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'mclarengt',
    fullName: 'McLaren GT🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3432,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'xxe',
    fullName: 'Ferrari 599XX EVO🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3433,
    carClass: 'B',
    rewardBP: 30,
  },
  {
    car_id: 'drakogte',
    fullName: 'Drako GTE',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3434,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'bt62',
    fullName: 'Brabham BT62🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3489,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'elva',
    fullName: 'McLaren Elva',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3530,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'rs01',
    fullName: 'Renault R.S. 01🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3571,
    carClass: 'B',
    rewardBP: 30,
  },
  {
    car_id: 'nsxgt3',
    fullName: 'Acura NSX GT3 EVO🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3585,
    carClass: 'B',
    rewardBP: 30,
  },
  {
    car_id: 'r390',
    fullName: 'Nissan R390 GT1🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 3627,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: '765lt',
    fullName: 'McLaren 765LT',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3651,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'm4gt3',
    fullName: 'BMW M4 GT3',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3665,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'miura',
    fullName: 'Lamborghini Miura Concept🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3688,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'eb110',
    fullName: 'Bugatti EB110🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3766,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'one77',
    fullName: 'Aston Martin One77',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3771,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'mc20',
    fullName: 'Maserati MC20🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 3772,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'stingray',
    fullName: 'Chevrolet Corvette Stingray',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3788,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'diablo',
    fullName: 'Lamborghini Diablo GT',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3869,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'reventon',
    fullName: 'Lamborghini Reventon Roadster🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 3983,
    carClass: 'B',
    rewardBP: 28,
  },
  {
    car_id: 'vantage',
    fullName: 'Aston Martin V12 Vantage 2022',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4072,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: '600lt',
    fullName: 'McLaren 600LT Spider',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4075,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'solus',
    fullName: 'Mclaren Solus GT🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4075,
    carClass: 'B',
    rewardBP: 35,
  },
  {
    car_id: 'evo',
    fullName: 'Lamborghini Huracan EVO Spyder',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4108,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'sesto',
    fullName: 'Lamborghini Sesto Elemento',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4183,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'apolloevo',
    fullName: 'Apollo EVO',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4265,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'revuelto',
    fullName: 'Lamborghini Revuelto',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4375,
    carClass: 'B',
    rewardBP: 40,
  },
  {
    car_id: 'laferrari',
    fullName: 'Ferrari LaFerrari',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3445,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: '003',
    fullName: 'Glickenhaus 003S',
    shortName: '',
    isKeyCar: false,
    star: 4,
    rank: 3534,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'n',
    fullName: 'Apollo N',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3548,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'p1',
    fullName: 'McLaren P1™',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3602,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'barchetta',
    fullName: 'Pagani Zonda HP Barchetta🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3678,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'centenario',
    fullName: 'Lamborghini Centenario',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3696,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'f12tdf',
    fullName: 'Ferrari F12tdf',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3705,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'gallardo',
    fullName: 'Lamborghini Gallardo LP 560-4',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 3706,
    carClass: 'A',
    rewardBP: 50,
  },
  {
    car_id: 'sv',
    fullName: 'Lamborghini Aventador SV Coupe',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3763,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'fxxk',
    fullName: 'Ferrari FXX K',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3821,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'legosennagtr',
    fullName: 'LEGO Technic Mclaren Senna GTR🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 3846,
    carClass: 'A',
    rewardBP: '?',
  },
  {
    car_id: 'c-x75',
    fullName: 'Jaguar C-X75',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3900,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'cgs',
    fullName: 'Chevrolet Corvette Grand Sport',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3906,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '33',
    fullName: 'Arrinera Hussarya 33',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3910,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'ap-0',
    fullName: 'Apex AP-0',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3922,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'murcielago',
    fullName: 'Lamborghini Murcielago LP 640 Roadster',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3924,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '1v10',
    fullName: 'VLF Force 1 V10',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3929,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '812',
    fullName: 'Ferrari 812 SuperFast',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3941,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'ie',
    fullName: 'Apollo IE',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3946,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '550',
    fullName: 'Sin R1 550',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3950,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'gt12',
    fullName: 'Aston Martin Vantage GT12',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3958,
    carClass: 'A',
    rewardBP: 35,
  },
  {
    car_id: 'avj',
    fullName: 'Lamborghini Aventador J',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4002,
    carClass: 'A',
    rewardBP: 50,
  },
  {
    car_id: 'carrera',
    fullName: 'Porsche Carrera GT',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4010,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'enzo',
    fullName: 'Ferrari Enzo Ferrari',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4014,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '911gt3',
    fullName: 'Porsche 911 GT3 RS',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4019,
    carClass: 'A',
    rewardBP: 50,
  },
  {
    car_id: 'at96',
    fullName: 'TechRules AT96 Track Version🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4020,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'sennagtr',
    fullName: 'McLaren Senna GTR',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4025,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'onyx',
    fullName: 'Peugeot Onyx',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4026,
    carClass: 'A',
    rewardBP: 33,
  },
  {
    car_id: 'zr1',
    fullName: 'Chevrolet Corvette ZR1',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4031,
    carClass: 'A',
    rewardBP: 50,
  },
  {
    car_id: 'scv12',
    fullName: 'Lamborghini Essenza SCV12🔑',
    shortName: '',
    isKeyCar: true,
    star: 5,
    rank: 4036,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'berlinetta',
    fullName: 'Puritalia Berlinetta',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4061,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'sc18',
    fullName: 'Lamborghini SC18🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4079,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'svj',
    fullName: 'Lamborghini Aventador SVJ Roadster',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4080,
    carClass: 'A',
    rewardBP: 70,
  },
  {
    car_id: '488gtbevo',
    fullName: 'Ferrari 488 GTB Challenge EVO🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4095,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'tachyon',
    fullName: 'Raesr Tachyon Speed🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4095,
    carClass: 'A',
    rewardBP: 38,
  },
  {
    car_id: 'citroengt',
    fullName: 'Citroen GT by Citroen\r\n',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4099,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'gtr-50',
    fullName: 'Nissan GTR-50 Italdesign',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4127,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'zondar',
    fullName: 'Pagani Zonda R🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4164,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: '9x8',
    fullName: 'Peugeot 9x8',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4172,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '007s',
    fullName: 'Glickenhaus 007S🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4192,
    carClass: 'A',
    rewardBP: 30,
  },
  {
    car_id: 'gtrneon',
    fullName: 'Nissan GT-R Neon Edition',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4201,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '935',
    fullName: 'Porsche 935(2019)🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4229,
    carClass: 'A',
    rewardBP: 45,
  },
  {
    car_id: 'victor',
    fullName: 'Aston Martin Victor',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4251,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'huayrar',
    fullName: 'Pagani Huayra R',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4259,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: '650s',
    fullName: 'Mclaren 650S GT3',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4266,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'interceptor',
    fullName: 'Security Interceptor',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4305,
    carClass: 'A',
    rewardBP: '?',
  },
  {
    car_id: 'xjr',
    fullName: 'Jaguar XJR-9',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4438,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'm600',
    fullName: 'Noble M600 Speedster',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4464,
    carClass: 'A',
    rewardBP: 40,
  },
  {
    car_id: 'valhalla',
    fullName: 'Aston Martin Valhalla Concept Car',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4515,
    carClass: 'A',
    rewardBP: 50,
  },
  {
    car_id: 'p72',
    fullName: 'De Tomaso P72🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4586,
    carClass: 'A',
    rewardBP: 45,
  },
  {
    car_id: 'vulcano',
    fullName: 'Icona Vulcano Titanium',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 3957,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'lykan',
    fullName: 'W Motors Lykan HyperSport',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4083,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: '918',
    fullName: 'Porsche 918 Spyder',
    shortName: '',
    isKeyCar: false,
    star: 5,
    rank: 4114,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'vanda',
    fullName: 'Vanda Electrics Dendrobium',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4124,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: '570',
    fullName: 'McLaren 570S Spider',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4135,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'veneno',
    fullName: 'Lamborghini Veneno',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4142,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'xj220',
    fullName: 'Jaguar XJ220 TWR🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4175,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'egoista',
    fullName: 'Lamborghini Egoista',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4213,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'me412',
    fullName: 'Chrysler ME412',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4241,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: '911gt2',
    fullName: 'Porsche 911 GT2 RS ClubSport🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4289,
    carClass: 'S',
    rewardBP: 28,
  },
  {
    car_id: 'bc',
    fullName: 'Pagani Huayra BC',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4292,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'aperta',
    fullName: 'Ferrari LaFerrari Aperta',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4293,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'tsr-s',
    fullName: 'Zenvo TSR-S🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4301,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'f1',
    fullName: 'Mclaren F1 LM🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4301,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'f8',
    fullName: 'Ferrari F8 Tributo',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4313,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'akylone',
    fullName: 'Genty Akylone',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4323,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'sc20',
    fullName: 'Lamborghini SC20🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4326,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'w12',
    fullName: 'Volkswagen W12 Coupe🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4334,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'nemesis',
    fullName: 'Trion Nemesis',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4344,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'spano',
    fullName: 'Spania GTA 2015 GTA Spano',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4385,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'sorpasso',
    fullName: 'FV Frangivento Sorpasso GT3🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4398,
    carClass: 'S',
    rewardBP: 45,
  },
  {
    car_id: 'terzo',
    fullName: 'Lamborghini Terzo Millennio',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4400,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'senna',
    fullName: 'McLaren Senna',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4407,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'veyron',
    fullName: 'Bugatti Veyron 16.4 Grand Sport Vitesse',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4411,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'evija',
    fullName: 'Lotus Evija',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4432,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: '1789',
    fullName: 'Vision 1789',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4442,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'fenyr',
    fullName: 'W Motors Fenyr SuperSport',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4479,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'valkyrie',
    fullName: 'Aston Martin Valkyrie',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4487,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'c1',
    fullName: 'Rimac Concept_One',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4490,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'ts1',
    fullName: 'Zenvo TS1 GT Anniversary',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4521,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'cs',
    fullName: 'Rimac Concept S',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4528,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'sf90',
    fullName: 'Ferrari SF90 Stradale',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4550,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'battista',
    fullName: 'Automobili Pininfarina Battista',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4551,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'imola',
    fullName: 'Pagani Imola',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4564,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'naran',
    fullName: 'Naran Hyper Coupe',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4564,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'lpi800',
    fullName: 'Lamborghini Countach LPI 800-4🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4571,
    carClass: 'S',
    rewardBP: 38,
  },
  {
    car_id: 'ep9',
    fullName: 'Nio EP9',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4571,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'speedtail',
    fullName: 'McLaren Speedtail',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4590,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'ff01',
    fullName: 'Faraday Future FFZero1',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4602,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'divo',
    fullName: 'Bugatti Divo',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4607,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'regera',
    fullName: 'Koenigsegg Regera',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4616,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'saleens7',
    fullName: 'Saleen S7 twin Turbo',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4629,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'lykanneon',
    fullName: 'W Motors Lykan HyperSoprt Neon Edition',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4636,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'ultimars',
    fullName: 'Ultima RS🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4650,
    carClass: 'S',
    rewardBP: 38,
  },
  {
    car_id: 'drakuma',
    fullName: 'Ajlani Drakuma',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4702,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'fordp1',
    fullName: 'Ford Team FordZilla P1',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4709,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'inferno',
    fullName: 'Inferno Automobili Inferno',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4725,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'torino',
    fullName: 'Torino Design Super Sport🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4741,
    carClass: 'S',
    rewardBP: 45,
  },
  {
    car_id: 'chiron',
    fullName: 'Bugatti Chiron',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4755,
    carClass: 'S',
    rewardBP: 30,
  },
  {
    car_id: 'bxr',
    fullName: 'BXR Bailey Blade GT1',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4759,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'ts900',
    fullName: 'Tushek TS 900 Racer Pro',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4782,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'millecavalli',
    fullName: 'Mazzanti Evantra Millecavalli',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4790,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: '1mw',
    fullName: 'Toroidion 1MW',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4808,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'settimo',
    fullName: 'Inferno Settimo Cerchio',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4817,
    carClass: 'S',
    rewardBP: '?',
  },
  {
    car_id: 'jesko',
    fullName: 'Koenigsegg Jesko🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4824,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'centodieci',
    fullName: 'Bugatti Centodieci🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4843,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'sian',
    fullName: 'Lamborghini Sian FKP 37🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4860,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'owl',
    fullName: 'Aspark Owl',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4861,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'c2',
    fullName: 'Rimac Nevera🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4897,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'agerars',
    fullName: 'Koenigsegg Agera RS',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4940,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'ssc',
    fullName: 'SSC Tuatara',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4930,
    carClass: 'S',
    rewardBP: 40,
  },
  {
    car_id: 'lykansecurity',
    fullName: 'W Motors Lykan Security',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 4977,
    carClass: 'S',
    rewardBP: '?',
  },
  {
    car_id: 'ccxr',
    fullName: 'Koenigsegg CCXR🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 4998,
    carClass: 'S',
    rewardBP: 45,
  },
  {
    car_id: 'lvn',
    fullName: 'Bugatti LA Voiture Noire🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 5055,
    carClass: 'S',
    rewardBP: 38,
  },
  {
    car_id: 'vayanne',
    fullName: 'Deus Vayanne',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 5082,
    carClass: 'S',
    rewardBP: 60,
  },
  {
    car_id: 'gemera',
    fullName: 'Koenigsegg Gemera🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 5092,
    carClass: 'S',
    rewardBP: 38,
  },
  {
    car_id: 'venomf5',
    fullName: 'Hennessey Venom F5',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 5128,
    carClass: 'S',
    rewardBP: 85,
  },
  {
    car_id: 'cc850',
    fullName: 'Koenigsegg CC850🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 5146,
    carClass: 'S',
    rewardBP: 45,
  },
  {
    car_id: 'bolide',
    fullName: 'Bugatti Bolide🔑',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 5385,
    carClass: 'R',
    rewardBP: 60,
  },
  {
    car_id: '300+',
    fullName: 'Bugatti Chiron Super Sport 300+',
    shortName: '',
    isKeyCar: true,
    star: 6,
    rank: 5602,
    carClass: 'R',
    rewardBP: 60,
  },
  {
    car_id: 'jkab',
    fullName: 'Koenigsegg Jesko Absolut',
    shortName: '',
    isKeyCar: false,
    star: 6,
    rank: 5664,
    carClass: 'R',
    rewardBP: 60,
  },
]
